import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Photo-Gallary",
  description: "Generated by create next app",
  icons: {
    icon: "/favicons/favicon.ico", // /public path
  },
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>{children}</body>
    </html>
  );
}
